name: Deploy MLOps API to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: clever-muse-483020-j5
          workload_identity_provider: projects/928351043184/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-actions@clever-muse-483020-j5.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: clever-muse-483020-j5

      - name: Build and push image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA .
          docker push gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mlops-api \
            --image gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
