name: Deploy MLOps API to Cloud Run

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gcloud
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-cli

      - name: Authenticate to Google Cloud
        run: |
          echo '${{ secrets.GCP_SA_KEY }}' > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project clever-muse-483020-j5

      - name: Build and push Docker image
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA .
          docker push gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mlops-api \
            --image gcr.io/clever-muse-483020-j5/mlops-api:$GITHUB_SHA \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --quiet
